name: Tests Contract TS
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  workflows:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install and test modules
        run: |
          cd ./contract-ts
          yarn
          yarn test
